name: Dependabot automation
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot_automation:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PR_URL: ${{github.event.pull_request.html_url}}
    steps:
      - name: Approve the PR
        run: gh pr review --approve "$PR_URL"
        continue-on-error: true
      - name: Enable auto-merge for the PR
        run: gh pr merge --auto --squash "$PR_URL"
